lib - final/lib/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shelf.urls')),
    path('accounts/', include('accounts.urls')),

]

lib - final/shelf/models.py
from django.db import models
from django.urls import reverse
import uuid  # Required for unique book instances
from django.contrib.auth.models import User
from datetime import date


class Genre(models.Model):
    name = models.CharField(max_length=200, help_text='Enter a book genre (e.g. Science Fiction)')

    def __str__(self):
        return self.name


class Book(models.Model):
    title = models.CharField(max_length=200)
    # Foreign Key used because book can only have one author, but authors can have multiple books
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    summary = models.TextField(max_length=1000, help_text='Enter a brief description of the book')
    isbn = models.CharField('ISBN', max_length=13,
                            help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
    # ManyToManyField used because genre can contain many books. Books can cover many genres.
    genre = models.ManyToManyField(Genre, help_text='Select a genre for this book')
    no_of_books=models.IntegerField()
    LOAN_STATUS = (
        ('o', 'On loan'),
        ('a', 'Available'),
    )
    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        default='a',
    )
    def __str__(self):
        return self.title

    class Meta:
        ordering = ['title']

    def get_absolute_url(self):
        # Returns the url to access a detail record for this book.
        return reverse('book_detail_view', args=[str(self.id)])



class BookInstance(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4,
                          help_text='Unique ID for this particular book across whole library')
    borrower=models.ForeignKey(User, on_delete=models.SET_NULL, null=True,blank=True,related_name='borrower')
    book=models.ForeignKey(Book, on_delete=models.SET_NULL,null=True)
    due_back=models.DateField(null=True,blank=True)
    fine=models.DecimalField(max_digits=10,decimal_places=2,default=0.0)
    reserver=models.ForeignKey(User, on_delete=models.SET_NULL,null=True,blank=True,related_name='reserver')
    RESERVATION_STATUS =(
        ('r', 'Reserved'),
        ('n', 'Not Reserved'),
    )
    reservations=models.CharField(
        max_length=1,
        choices=RESERVATION_STATUS,
        default='n',
    )

    LOAN_STATUS = (
        ('o', 'On loan'),
        ('a', 'Available'),
    )
    status=models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        default='a',
    )

    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False

    def __str__(self):
        return self.book.title

    # def __str__(self):
    #     return f'{self.id} ({self.book.title})'

    def get_absolute_url(self):
        return reverse('book_loan_view', args=[str(self.id)])

    def get_absolute_url_for_return(self):
        return reverse('return_book', args=[str(self.id)])

    def get_absolute_url_for_renewal(self):
        return reverse('renew_book', args=[str(self.id)])

    def get_absolute_url_for_reserve(self):
        return reverse('reserve_book', args=[str(self.id)])

    def get_absolute_url_for_unreserve(self):
        return reverse('unreserve_book', args=[str(self.id)])

    # def get_absolute_url_for_fine(self):
    #     return reverse('fine', args=[str(self.id)])




# class BookInstance(models.Model):
#     borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
#
#     id = models.UUIDField(primary_key=True, default=uuid.uuid4,
#                           help_text='Unique ID for this particular book across whole library')
#     book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True)
#     imprint = models.CharField(max_length=200)
#     due_back = models.DateField(null=True, blank=True)
#
#     @property
#     def is_overdue(self):
#         if self.due_back and date.today() > self.due_back:
#             return True
#         return False
#
#     LOAN_STATUS = (
#         ('m', 'Maintenance'),
#         ('o', 'On loan'),
#         ('a', 'Available'),
#         ('r', 'Reserved'),
#     )
#
#     status = models.CharField(
#         max_length=1,
#         choices=LOAN_STATUS,
#         blank=True,
#         default='m',
#         help_text='Book availability',
#     )
#
#     class Meta:
#         ordering = ['due_back']
#
#     def __str__(self):
#         return f'{self.id} ({self.book.title})'


class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)
#    books = models.ForeignKey(Book,on_delete=models.CASCADE)
    author_id=models.IntegerField()

    class Meta:
        ordering = ['first_name','last_name']

    # def get_absolute_url(self):
    #     return reverse('books_of_author', args=[str(self.id)])
    def get_absolute_url(self):
        return reverse('books_of_author',args=[str(self.id)])

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

lib - final/templates/author_list.html
{% extends 'base.html' %}

{% block content %}
<h1 align="center">Authors</h1>
{% for i in author_list %}
<div class="card">
<a href="{{i.get_absolute_url}}">{{ i.first_name }} {{i.last_name}}</a><br>
    </div>
<br>
{% endfor %}

{% endblock%}

lib - final/templates/base.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}<title>Local Library</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <!-- Add additional CSS in static file -->
        <link href="https://use.fontawesome.com/releases/v5.0.7/css/all.css" rel="stylesheet">
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body class="body">

  <div class="container">
    <div class="row">
      <div class="col-sm-2">
      {% block sidebar %}
        <ul class="sidebar-nav sidenav ">
                                    {% if user.is_authenticated %}
									<div class="name">hello {{user.get_username}}</div>
									<li><a href="{% url 'logout' %}">Logout</a></li>
									{% else %}
									<li><a href="{% url 'login' %}">Login</a></li>
									<li><a href="{% url 'register' %}">Register</a></li>
									{% endif %}
          <li><a href="{% url 'home' %}">Home <i class="fas fa-home"></i></a></li>
            <li><a href="{% url 'book_list_view'%}">All books <i class="fas fa-book"></i></a></li>
          <li><a href="{% url 'author_list' %}">All authors </a></li>
            {% if user.is_authenticated %}
            <li><a href="{% url 'user_book_list' %}">My Books <i class="fas fa-book-reader"></i></a></li>
            {% endif %}
        </ul>
     {% endblock %}
      </div>
      <div class="col-sm-10 box text">{% block content %}{% endblock %}</div>
    </div>
  </div>
</body>
</html>

lib - final/templates/book_detail.html
{% extends "base.html" %}

{% block content %}
  <h1 align="center">Title: {{ book_detail.title }}</h1>
<div class="card">

  <p><strong>Author:</strong> <a href="">{{ book_detail.author }}</a></p> <!-- author detail link not yet defined -->
  <p><strong>Summary:</strong> {{ book_detail.summary }}</p>
  <p><strong>ISBN:</strong> <a href="https://www.isbn-international.org/content/what-isbn">{{ book_detail.isbn }}</a></p>
  <p><strong>Genre:</strong>
    {% for genre in book_detail.genre.all %}
    {{ genre }}
    {% endfor %}
  </p>
  <p><strong>No of books</strong> {{ book_detail.no_of_books }}</p>
  </div>


<!--  <div style="margin-left:20px;margin-top:20px">-->


    <!--<p class="{% if book_detail.status == 'a' %}text-success{% elif book_detail.status == 'm' %}text-danger{% else %}text-warning{% endif %}">
          ({{book_detail.get_status_display}})
        </p>
        (date.today()-copy.due_back).days*100
        -->
  {% if user.is_authenticated %}

    <h4 align="center">Copies</h4>
<div class="card">
<ul>
    {% for copy in book_detail.bookinstance_set.all %}
    <li class="">
      <hr>
          <p class="text-muted"><strong>Id:</strong> {{copy.id}}</p>

      <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' or copy.is_overdue %}text-danger{% else %}text-warning{% endif %}">{{ copy.get_status_display }}</p>
      {% if copy.status != 'a' %}
        <p><strong>Due to be returned:</strong> {{copy.due_back}}</p>
      {% endif %}
      <p>
  {% if user.is_authenticated and copy.status == 'a' %}
  <a href="{{copy.id}}/borrow">Borrow</a>
  {% endif %}
  </p>


    {% if copy.borrower != user and copy.reservations != 'r' and copy.status != 'a' %}
        <a href="{{copy.get_absolute_url_for_reserve}}" type="submit">reserve</a>
    {% endif %}

    {% if copy.reserver != user and copy.reservations == 'r'%}
      <p>Already Reserved</p>
    {% endif %}

    {% if copy.reserver == user and copy.reservations == 'r'%}
    <a href="{{copy.get_absolute_url_for_unreserve}}" type="submit">unreserve</a>
    {% endif %}

    {% if copy.status == 'o' and copy.borrower == user %}
    <a href="{{copy.get_absolute_url_for_return}}" type="submit">return</a>/
    <a href="{{copy.get_absolute_url_for_renewal}}" type="submit">renew</a>

    {% endif %}
    </li>
  <br>
    {% endfor %}
      </ul>
    <br>
        {% endif %}

  </div>
{% endblock %}

lib - final/templates/book_list.html
{% extends "base.html" %}

{% block content %}
  <h1 align="center">Book List</h1>
  {% if book_list %}
  <ul>
    {% for book in book_list %}
      <li class="card">
        <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{book.author}}) <br>


        <!--<p class="{% if book.status == 'a' %}text-success{% elif book.status == 'm' %}text-danger{% else %}text-warning{% endif %}">
          ({{book.get_status_display}})
        </p>-->

      </li>
    <br>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no books in the library.</p>
  {% endif %}
{% endblock %}

lib - final/templates/books_of_author.html
{% extends "base.html" %}

{% block content %}
<h1 align="center">Books of {{author}}</h1>
<ul>
{% for i in books_of_author %}
<li class="card">
    <a href="{{ i.get_absolute_url }}">{{i.title}}</a><br>
</li>
<br>
{% endfor %}
    </ul>
<br>
<!--{{books_of_author_qs.title}}-->
{% endblock %}

lib - final/templates/borrow.html
{% extends 'base.html' %}
{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-default btn-primary" type="submit">Submit</button>
</form>
{% endblock %}

lib - final/templates/index.html
{% extends "base.html" %}

{% block content %}
  <h1 align="center">Local Library Home</h1>
<div class="card" align="center">
  <h5  >Welcome to LocalLibrary !!!</h5>
  <p>created by:-</p>
  <p>Ashay Mehta(60004180010)</p>
  <p>Bhavya Lakhani(60004180014)</p>
  <p>Chinmay Jain(60004180015)</p>
  </div>
  <h2 align="center">Dynamic content</h2>
<div class="card">
  <p>The library has the following record counts:</p>
  <ul >
    <li><strong>Books:</strong> {{ num_books }}</li>
    <!--<li><strong>Copies:</strong> {{ num_instances }}</li>-->
<!--    <li><strong>Books available:</strong> {{ num_instances_available }}</li>-->
    <li><strong>Authors:</strong> {{ num_authors }}</li>
<!--        <li><strong>sessions:</strong> {{ num_visits }}</li>-->



  </ul>
  </div>
{% endblock %}

lib - final/templates/register.html
{% extends 'base.html' %}
{%load crispy_forms_tags%}
{% block content %}

{%for i in messages%}
{{i}}
{% endfor %}

<div class="container">
<h1>Registration form</h1>
<form method="post">
    {% csrf_token %}
    {{form2|crispy}}
    <br>
    <input type="submit" class=" btn btn-default btn-primary" value="submit">
</form>
    </div>
{% endblock %}


<!--<form action="register" method="post">
    {% csrf_token%}
    Enter username:<input type="text" name="username" placeholder="username"><br>
    Enter password:<input type="password" name="password1" placeholder="password"><br>
    Re enter password:<input type="password" name="password2" placeholder="confirm password"><br>
    <input type="submit">
</form>

<div>
    {% for i in messages %}
    <h3>{{i}}</h3>
    {% endfor %}
</div>-->

lib - final/templates/renew.html
{% extends "base.html" %}
{%load crispy_forms_tags%}
{% block content %}
  <h1 align="center">Renew: {{ book_instance.book.title }}</h1>
<div class="card">
{% if book_instance.reservations != 'r' %}
  <p>Borrower: {{ book_instance.borrower }}</p>

  <p{% if book_instance.is_overdue %} class="text-danger"{% endif %}>Due date: {{ book_instance.due_back }}</p>
{% endif %}
  </div>
  {% if book_instance.reservations != 'r' %}
  <form action="" method="post">
    {% csrf_token %}

    {{ form|crispy }}

    <input class="btn btn-default btn-primary" type="submit" value="Submit">
  </form>
  {% else %}
  <p>cannot renew it has been reserved</p>
  {% endif %}
{% endblock %}

lib - final/templates/reserve.html
{% extends "base.html" %}
{%load crispy_forms_tags%}
{% block content %}
  <h1>Reserve: {{ book_instance.book.title }}</h1>
  <p{% if book_instance.is_overdue %} class="text-danger"{% endif %}>Due date: {{ book_instance.due_back }}</p>

  <form action="" method="post">
    {% csrf_token %}

    {{ form|crispy }}

    <input class="btn btn-default btn-primary" type="submit" value="Submit">
  </form>
{% endblock %}

lib - final/templates/return.html
{% extends "base.html" %}

{% block content %}
<h2>Fine : {{book_detail_instance.fine}}</h2>
<form method="post">
    {% csrf_token %}
<h1>are u confirm u want to return this book ?</h1>
<input class="btn btn-default btn-primary" type="submit" value="Yes">
    <a href="{% url 'book_detail_view' to_be_returned_book.book.pk %}" class="btn btn-default btn-primary" type="submit">No</a>

</form>
{% endblock %}

lib - final/templates/unreserve.html
{% extends "base.html" %}

{% block content %}
<form method="post">
    {% csrf_token %}
<h1>are u confirm u want to unreserve this book ?</h1>
<input class="btn btn-default btn-primary" type="submit" value="Yes">
    <a href="{% url 'book_detail_view' book_instance.book.pk %}" class="btn btn-default btn-primary" type="submit">No</a>

</form>
{% endblock %}

lib - final/templates/userlist_view.html
                        {% extends "base.html" %}

{% block content %}
    <h1 align="center">Borrowed books</h1>

    {% if user_book_list %}
    <ul>

      {% for bookinst in user_book_list %}
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %} card">
        <a href="{% url 'book_detail_view' bookinst.book.pk %}">{{bookinst.book.title}}</a> ({{ bookinst.due_back }})
      </li>
        <br>
      {% endfor %}
    </ul>

    {% else %}
      <p align="center">There are no books borrowed.</p>
    {% endif %}

     <h1 align="center">Resrved Books</h1>
      {% if user_reserve_book_list %}
    <ul>

      {% for bookinst in user_reserve_book_list %}
      <li class="card">
        <a href="{% url 'book_detail_view' bookinst.book.pk %}">{{bookinst.book.title}}</a> ({{ bookinst.due_back }})
      </li>
        <br>
      {% endfor %}
    </ul>

    {% else %}
      <p align="center">There are no books reserved.</p>
    {% endif %}

{% endblock %}