ecommerce/core/urls.py
from django.urls import path
from . import views

urlpatterns = [
    #path('',views.item_list,name='item_list'),
    path('',views.ItemListView.as_view(), name='item_list'),
    #path('detail/<slug>/',views.DetailView.as_view(), name='detail'),
    path('detail/<slug>/',views.detail_view, name='detail'),
    path('add-to-cart/<slug>/',views.add_to_cart, name='add_to_cart'),
    path('remove-from-cart/<slug>/', views.remove_from_cart, name='remove_from_cart'),
    path('order-summary', views.OrderSummaryView.as_view(), name='order_summary'),
    path('add-to-order-cart/<slug>/',views.add_to_order_cart, name='add_to_order_cart'),
    path('remove-from-order-cart/<slug>/', views.remove_from_order_cart, name='remove_from_order_cart'),
    path('checkout', views.CheckoutView.as_view(), name='checkout'),
    path('payment',views.Payment.as_view(), name='payment'),

]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('myapp',include('myapp.urls')),
    path('', include('core.urls')),

]

ecommerce/core/models.py
from django.db import models
from django.contrib.auth.models import User
from django.shortcuts import reverse

CATEGORY_CHOICES = (
    ('S','Shirts'),
    ('SW','SportsWear'),
    ('OW','Outwear'),
)
LABEL_CHOICES = (
    ('P','primary'),
    ('S','secondary'),
    ('D','danger'),
)


class Item(models.Model):
    title = models.CharField(max_length=100)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    category = models.CharField(choices=CATEGORY_CHOICES,max_length=2)
    label = models.CharField(choices=LABEL_CHOICES,max_length=1)
    slug = models.SlugField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("detail",kwargs={'slug':self.slug})

    def get_add_to_cart_url(self):
        return reverse("add_to_cart",kwargs={'slug':self.slug})

    def get_remove_from_cart_url(self):
        return reverse("remove_from_cart",kwargs={'slug':self.slug})


class OrderItem(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True,blank=True)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item,on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"

    def get_total_item_price(self):
        return self.quantity*self.item.price

    def get_total_discount_item_price(self):
        return self.quantity*self.item.discount_price

    def get_amount_saved(self):
        return self.get_total_item_price()-self.get_total_discount_item_price()

    def get_total_price(self):
        if self.item.discount_price:
            return self.get_total_discount_item_price()
        else:
            return self.get_total_item_price()


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    def get_final_price(self):
        total=0
        for order_item in self.items.all():
            total+=order_item.get_total_price()
        return total


class Payment(models.Model):
    user=models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)

ecommerce/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>home</title>
</head>
<body>
<header>
    <nav>
        <ul>
            <li>home</li>
            {% if user.is_authenticated %}
            <li>hello {{user.username}}</li>
            <li><a href="{% url 'logout' %}">logout</a></li>
            {% else %}
            <li><a href="{% url 'register' %}">register</a></li>
            <li><a href="{% url 'login' %}">login</a></li>
            {% endif %}

        </ul>
    </nav>
</header>
{% block content%}
{% endblock %}
</body>
</html>

ecommerce/templates/checkout-page.html
{% extends 'home.html' %}
{% block content %}
  <!--Main layout-->
  <main class="mt-5 pt-4">
    <div class="container wow fadeIn">

      <!-- Heading -->
      <h2 class="my-5 h2 text-center">Checkout form</h2>

      <!--Grid row-->
      <div class="row">

        <!--Grid column-->
        <div class="col-md-8 mb-4">

          <!--Card-->
          <div class="card">

            <!--Card content-->
            <form method="post" class="card-body" >
            {% csrf_token %}
              <!--Grid row-->
              <div class="row">



              </div>
              <!--Grid row-->
              <!--Username-->
              <div class="md-form input-group pl-0 mb-5">
                <div class="input-group-prepend">
                  <span class="input-group-text" id="basic-addon1">Username</span>
                </div>
                <span class="form-control">{{user.username}}</span>

              </div>

              <!--email-->
              <div class="md-form mb-5">
                <input type="text" id="email" class="form-control" placeholder="youremail@example.com">
                <label for="email" class="">Email (optional)</label>
              </div>

              <!--address-->
              <div class="md-form mb-5">
                {{form.street_address}}
              </div>

              <!--address-2-->
              <div class="md-form mb-5">
                {{form.appartment_address}}
              </div>

              <!--Grid row-->
              <div class="row">

                <!--Grid column-->
                <div class="col-lg-4 col-md-12 mb-4">

                  <label for="country">Country</label>
                  <select class="custom-select d-block w-100" id="country" required>
                    <option value="">Choose...</option>
                    <option>United States</option>
                    <option>India</option>
                  </select>
                  <div class="invalid-feedback">
                    Please select a valid country.
                  </div>

                </div>
                <!--Grid column-->

                <!--Grid column-->
                <div class="col-lg-4 col-md-6 mb-4">

                  <label for="state">State</label>
                  <select class="custom-select d-block w-100" id="state" required>
                    <option value="">Choose...</option>
                    <option>California</option>
                    <option>Maharashtra</option>
                  </select>
                  <div class="invalid-feedback">
                    Please provide a valid state.
                  </div>

                </div>
                <!--Grid column-->

                <!--Grid column-->
                <div class="col-lg-4 col-md-6 mb-4">

                  <label id="zip" >Zip</label>
                  {{form.zip}}
                    Zip code required.
                  </div>

                </div>
                <!--Grid column-->

              </div>
              <!--Grid row-->

              <hr>

              <div class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" name="same_billing_address" id="same-address">
                <label class="custom-control-label" for="same-address">Shipping address is the same as my billing address</label>
              </div>
              <div class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" name="save_info" id="save-info">
                {{save_info}}
                <label class="custom-control-label" for="save-info">Save this information for next time</label>
              </div>

              <hr>

              <div class="d-block my-3">
                {% for value,name in form.fields.payment_option.choices %}
              <div class="custom-control custom-radio">
              <input id="{{ name }}" name="payment_option" value="{{ value }}" type="radio"
                                      class="custom-control-input" required>
              <label class="custom-control-label" for="{{ name }}">{{ name }}</label>
              </div>
            {% endfor %}


              </div>
          <button class="btn" type="submit" >submit</button>
            </form>

          </div>
          <!--/.Card-->

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-4 mb-4">

          <!-- Heading -->
          <h4 class="d-flex justify-content-between align-items-center mb-3">
            <span class="text-muted">Your cart</span>
            <span class="badge badge-secondary badge-pill">3</span>
          </h4>

          <!-- Cart -->
          <ul class="list-group mb-3 z-depth-1">
            <li class="list-group-item d-flex justify-content-between lh-condensed">
              <div>
                <h6 class="my-0">Product name</h6>
                <small class="text-muted">Brief description</small>
              </div>
              <span class="text-muted">$12</span>
            </li>
            <li class="list-group-item d-flex justify-content-between lh-condensed">
              <div>
                <h6 class="my-0">Second product</h6>
                <small class="text-muted">Brief description</small>
              </div>
              <span class="text-muted">$8</span>
            </li>
            <li class="list-group-item d-flex justify-content-between lh-condensed">
              <div>
                <h6 class="my-0">Third item</h6>
                <small class="text-muted">Brief description</small>
              </div>
              <span class="text-muted">$5</span>
            </li>
            <li class="list-group-item d-flex justify-content-between bg-light">
              <div class="text-success">
                <h6 class="my-0">Promo code</h6>
                <small>EXAMPLECODE</small>
              </div>
              <span class="text-success">-$5</span>
            </li>
            <li class="list-group-item d-flex justify-content-between">
              <span>Total (USD)</span>
              <strong>$20</strong>
            </li>
          </ul>
          <!-- Cart -->

          <!-- Promo code -->
          <form class="card p-2">
            <div class="input-group">
              <input type="text" class="form-control" placeholder="Promo code" aria-label="Recipient's username" aria-describedby="basic-addon2">
              <div class="input-group-append">
                <button class="btn btn-secondary btn-md waves-effect m-0" type="button">Redeem</button>
              </div>
            </div>
          </form>
          <!-- Promo code -->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

    </div>
  </main>
  <!--Main layout-->

 {% endblock %}

ecommerce/templates/home-page.html
{% extends 'home.html' %}

  {% block content %}
  <!--Main layout-->
  <main>
    <div class="container">

      <!--Navbar-->
      <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-5 mb-5">

        <!-- Navbar brand -->
        <span class="navbar-brand">Categories:</span>

        <!-- Collapse button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
          aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Collapsible content -->
        <div class="collapse navbar-collapse" id="basicExampleNav">

          <!-- Links -->
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">All
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Shirts</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Sport wears</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Outwears</a>
            </li>

          </ul>
          <!-- Links -->

          <form class="form-inline">
            <div class="md-form my-0">
              <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
            </div>
          </form>
        </div>
        <!-- Collapsible content -->

      </nav>
      <!--/.Navbar-->

      <!--Section: Products v.3-->
      <section class="text-center mb-4">

        <!--Grid row-->
        <div class="row wow fadeIn">
          {% for i in items %}
          <!--Grid column-->
          <div class="col-lg-3 col-md-6 mb-4">

            <!--Card-->
            <div class="card">

              <!--Card image-->
              <div class="view overlay">
                <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/12.jpg" class="card-img-top"
                  alt="">
                <a>
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>
              <!--Card image-->

              <!--Card content-->
              <div class="card-body text-center">
                <!--Category & Title-->
                <a href="" class="grey-text">
                  <h5>{{i.get_category_display}}</h5>
                </a>
                <h5>
                  <strong>
                    <a href="{{i.get_absolute_url}}" class="dark-grey-text">{{i.title}}
                      <span class="badge badge-pill {{i.get_label_display}}-color">NEW</span>
                    </a>
                  </strong>
                </h5>

                <h4 class="font-weight-bold blue-text">
                  {% if i.discount_price %}
                  <strong>
                    <span><del>{{i.price}}</del></span>
                    <span>{{i.discount_price}}$</span>
                  </strong>
                  {% else %}
                  <strong>{{i.price}}</strong>
                  {% endif %}
                </h4>

              </div>
              <!--Card content-->

            </div>
            <!--Card-->

          </div>
          <!--Grid column-->
          {% endfor %}
          
        </div>
        <!--Grid row-->

      </section>
      <!--Section: Products v.3-->

      <!--Pagination-->
      <nav class="d-flex justify-content-center wow fadeIn">
        <ul class="pagination pg-blue">

          <!--Arrow left-->
          <li class="page-item disabled">
            <a class="page-link" href="#" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Previous</span>
            </a>
          </li>

          <li class="page-item active">
            <a class="page-link" href="#">1
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="page-item">
            <a class="page-link" href="#">2</a>
          </li>
          <li class="page-item">
            <a class="page-link" href="#">3</a>
          </li>
          <li class="page-item">
            <a class="page-link" href="#">4</a>
          </li>
          <li class="page-item">
            <a class="page-link" href="#">5</a>
          </li>

          <li class="page-item">
            <a class="page-link" href="#" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Next</span>
            </a>
          </li>
        </ul>
      </nav>
      <!--Pagination-->

    </div>
  </main>
  <!--Main layout-->
  {% endblock %}

ecommerce/templates/home.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>Material Design Bootstrap</title>
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'https://use.fontawesome.com/releases/v5.11.2/css/all.css' %}">
  <!-- Bootstrap core CSS -->
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <!-- Material Design Bootstrap -->
  <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
  <!-- Your custom styles (optional) -->
  <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
  <style type="text/css">
    html,
    body,
    header,
    .carousel {
      height: 60vh;
    }

    @media (max-width: 740px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

    @media (min-width: 800px) and (max-width: 850px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

  </style>
</head>

<body>

  <!-- Navbar -->
    <nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
    <div class="container">

      <!-- Brand -->
      <a class="navbar-brand waves-effect" href="{% static 'https://mdbootstrap.com/docs/jquery/' %}" target="_blank">
        <strong class="blue-text">DJ Ecommerce</strong>
      </a>

      <!-- Collapse -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Links -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <!-- Left -->
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link waves-effect" href="{% url 'item_list' %}">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="#" >CheckOut</a>
          </li>


        </ul>

        <!-- Right -->
        <ul class="navbar-nav nav-flex-icons">
            {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'order_summary' %}">
              <span class="badge red z-depth-1 mr-1"> 1 </span>
              <i class="fas fa-shopping-cart"></i>
              <span class="clearfix d-none d-sm-inline-block"> Cart </span>
            </a>
          </li>
            <li class="nav-item">
              <a class="nav-link waves-effect" href="{% url 'logout' %}">
              <span class="clearfix d-none d-sm-inline-block"> Logout </span>
            </a>
          </li>
            {% else %}
            <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'login' %}">
              <span class="clearfix d-none d-sm-inline-block" > Login </span>
            </a>
            </li>
            <li class="nav-item">
             <a class="nav-link waves-effect" href="{% url 'register' %}">
                <span class="clearfix d-none d-sm-inline-block"  > Signup </span>
            </a>

          </li>
        {% endif %}
        </ul>

      </div>

    </div>
  </nav>
  <!-- Navbar -->

  {% block content %}
  {% endblock %}

 <!--Footer-->
  <footer class="page-footer text-center font-small mt-4 wow fadeIn">



    <hr class="my-4">

    <!-- Social icons -->
    <div class="pb-4">
      <a href="https://www.facebook.com/mdbootstrap" >
        <i class="fab fa-facebook-f mr-3"></i>
      </a>

      <a href="{% static 'https://twitter.com/MDBootstrap' %}" target="_blank">
        <i class="fab fa-twitter mr-3"></i>
      </a>

      <a href="https://www.youtube.com/watch?v=7MUISDJ5ZZ4" target="_blank">
        <i class="fab fa-youtube mr-3"></i>
      </a>

      <a href="{% static 'https://plus.google.com/u/0/b/107863090883699620484' %}" target="_blank">
        <i class="fab fa-google-plus-g mr-3"></i>
      </a>

      <a href="{% static 'https://dribbble.com/mdbootstrap' %}" target="_blank">
        <i class="fab fa-dribbble mr-3"></i>
      </a>

      <a href="{% static 'https://pinterest.com/mdbootstrap' %}" target="_blank">
        <i class="fab fa-pinterest mr-3"></i>
      </a>

      <a href="{% static 'https://github.com/mdbootstrap/bootstrap-material-design' %}" target="_blank">
        <i class="fab fa-github mr-3"></i>
      </a>

      <a href="{% static 'http://codepen.io/mdbootstrap/' %}" target="_blank">
        <i class="fab fa-codepen mr-3"></i>
      </a>
    </div>
    <!-- Social icons -->

    <!--Copyright-->
    <div class="footer-copyright py-3">
      © 2019 Copyright:
      <a href="{% static 'https://mdbootstrap.com/education/bootstrap/' %}" target="_blank"> MDBootstrap.com </a>
    </div>
    <!--/.Copyright-->

  </footer>
  <!--/.Footer-->

  <!-- SCRIPTS -->
  <!-- JQuery -->
  <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
  <!-- Bootstrap tooltips -->
  <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
  <!-- Initializations -->
  <script type="text/javascript">
    // Animations initialization
    new WOW().init();

  </script>
</body>

</html>

ecommerce/templates/item_list.html
{% extends 'base.html' %}

{% block content %}
<h1>hello</h1>
{% for i in items %}

    {{i}}
    <br>
{% endfor %}
{% endblock %}

ecommerce/templates/login.html
{% extends 'home.html' %}
{%block content%}
<div class="container mt-5 mb-5">
    <div class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-5 mb-5">
        <div class="container mt-5 mb-5">

<section class="text-center mb-4">
<form method="post">
    {% csrf_token %}
    {{form.as_p}}

    <button type="submit">login</button>
</form>
</section>

            </div>
    </div>
    </div>
<div>
    {% for i in messages %}
    <h1>{{i}}</h1>
    {% endfor %}
</div>
{% endblock %}

ecommerce/templates/order_summary.html
{% extends 'home.html' %}

{% block content %}
<div class="container">

      <!--Navbar-->
      <div class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-5 mb-5">
        <div class="container ">
          <h1>Order summary </h1>
        </div>
      </div>
</div>

<div class="table-responsive text-nowrap">

  <table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">item-title</th>
        <th scope="col">price</th>
        <th scope="col">quantity</th>
        <th scope="col">total price</th>
      </tr>
    </thead>
    <tbody>
    {% for object in object.items.all %}
      <tr>
        <th scope="row">{{forloop.counter}}</th>
        <td>{{object.item.title}}</td>
        <td>{{object.item.price}}</td>
        <td>
          <a class=" btn mr-2" href="{% url 'remove_from_order_cart' object.item.slug %}">-</a>
          {{object.quantity}}
          <a class="btn ml-2" href="{% url 'add_to_order_cart' object.item.slug %}">+</a>
        </td>
        <td>
          {% if object.item.discount_price %}
          {{object.get_total_discount_item_price}}
          (saving {{object.get_amount_saved}})
          {% else %}
          {{object.get_total_item_price}}
          {% endif %}
        </td>

      </tr>
    {% endfor %}
    <tr>
      <td colspan="4">order total</td>
      <td>{{object.get_final_price}}</td>
    </tr>
    <tr>

      <td colspan="5">

        <a class="btn btn-warning float-right ml-2" href="{% url 'checkout' %}">proceed to checkout</a>
        <a class="btn btn-primary float-right" href="/">continue shopping</a>
      </td>
    </tr>

    </tbody>
  </table>

</div>

{% endblock %}

ecommerce/templates/payment.html
{% extends 'home.html' %}
{% block content %}
<form class="container">

      <!--Navbar-->
      <div class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-5 mb-5">
<h2>Buy for $5.00</h2>
<form action="{% url 'payment' %}" method="post">
  {% csrf_token %}
  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="{{ key }}"
          data-description="A Django Charge"
          data-amount="500"
          data-locale="auto"></script>

              </div>
</form>



            <h4 class="d-flex justify-content-between align-items-center mb-3">
            <span class="text-muted">Your cart</span>
            <span class="badge badge-secondary badge-pill">3</span>
          </h4>

          <!-- Cart -->
          <ul class="list-group mb-3 z-depth-1">
            <li class="list-group-item d-flex justify-content-between lh-condensed">
              <div>
                <h6 class="my-0">Product name</h6>
                <small class="text-muted">Brief description</small>
              </div>
              <span class="text-muted">$12</span>
            </li>
            <li class="list-group-item d-flex justify-content-between lh-condensed">
              <div>
                <h6 class="my-0">Second product</h6>
                <small class="text-muted">Brief description</small>
              </div>
              <span class="text-muted">$8</span>
            </li>
            <li class="list-group-item d-flex justify-content-between lh-condensed">
              <div>
                <h6 class="my-0">Third item</h6>
                <small class="text-muted">Brief description</small>
              </div>
              <span class="text-muted">$5</span>
            </li>
            <li class="list-group-item d-flex justify-content-between bg-light">
              <div class="text-success">
                <h6 class="my-0">Promo code</h6>
                <small>EXAMPLECODE</small>
              </div>
              <span class="text-success">-$5</span>
            </li>
            <li class="list-group-item d-flex justify-content-between">
              <span>Total (USD)</span>
              <strong>$20</strong>
            </li>
          </ul>
          <!-- Cart -->
              <hr class="mb-4">
              <button class="btn btn-primary btn-lg btn-block" type="submit">Continue to checkout</button>
    </div>

{% endblock %}

ecommerce/templates/product-page.html
{% extends 'home.html' %}

{% block content %}
  <div class="mt-5 pt-4">
  {% if messages %}
  {% for message in messages %}
    {{message}}
  {% endfor %}
  {% endif %}
    </div>

  <!--Main layout-->
  <main class="mt-5 pt-4">
    <div class="container dark-grey-text mt-5">

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/14.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <!--Content-->
          <div class="p-4">

            <div class="mb-3">
              <a href="">
                <span class="badge {{obj.get_label_display}}-color mr-1">{{obj.get_category_display}}</span>
              </a>
              <a href="">
                <span class="badge blue mr-1">New</span>
              </a>
              <a href="">
                <span class="badge red mr-1">Bestseller</span>
              </a>
            </div>
            {% if obj.discount_price %}
            <p class="lead">
              <span class="mr-1">
                <del>{{obj.price}}</del>
              </span>
              <span>{{obj.discount_price}}</span>
            </p>
            {% else %}
            <p class="lead">
              <span class="mr-1">
                {{obj.price}}
              </span>
            </p>
            {% endif %}


            <p class="lead font-weight-bold">Description</p>

            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Et dolor suscipit libero eos atque quia ipsa
              sint voluptatibus!
              Beatae sit assumenda asperiores iure at maxime atque repellendus maiores quia sapiente.</p>
              
            <form class="d-flex justify-content-left">
              <!-- Default input -->
              <input type="number" value="1" aria-label="Search" class="form-control" style="width: 100px">
             

            </form>
            
            <a href="{{obj.get_add_to_cart_url}}" class="btn btn-primary btn-md my-0 p" >Add to cart
              <i class="fas fa-shopping-cart ml-1"></i>
            </a>
            <a href="{{obj.get_remove_from_cart_url}}" class="btn btn-danger btn-md my-0 p" >Remove from cart
              <i class="fas fa-shopping-cart ml-1"></i>
            </a>

          </div>
          <!--Content-->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <hr>

      <!--Grid row-->
      <div class="row d-flex justify-content-center wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 text-center">

          <h4 class="my-4 h4">Additional information</h4>

          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus suscipit modi sapiente illo soluta odit
            voluptates,
            quibusdam officia. Neque quibusdam quas a quis porro? Molestias illo neque eum in laborum.</p>

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-lg-4 col-md-12 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/11.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/12.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/13.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

    </div>
  </main>
  <!--Main layout-->

  {% endblock %}

ecommerce/templates/register.html
{% extends 'home.html' %}
{% block content %}
<div class="container mt-5 mb-5">
    <div class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-5 mb-5">
        <div class="container mt-5 mb-5">

<form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">submit</button>

</form>
        </div>
    </div>
</div>

<div>
    {% for i in messages %}
    <h1>{{i}}</h1>
    {% endfor %}
</div>
{% endblock%}